FROM envoyproxy/envoy-dev:latest

RUN apt-get update \
    && apt-get install --no-install-recommends -y curl \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /tmp/* /var/tmp/* /var/lib/apt/lists/*
COPY ./front-envoy.yaml /etc/front-envoy.yaml

COPY ./certs /certs
RUN chmod go+r /etc/front-envoy.yaml \
	&& chmod go+x /certs \
	&& chmod go+r /certs/*
    
CMD ["/usr/local/bin/envoy", "-c", "/etc/front-envoy.yaml", "--service-cluster", "front-proxy"]
